-- MySQL Script generated by MySQL Workbench
-- Fri May  5 01:53:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tallerDb
-- -----------------------------------------------------
-- borrar db si ya existe
DROP DATABASE IF EXISTS `tallerDb`;
-- -----------------------------------------------------
-- Schema tallerDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallerDb` DEFAULT CHARACTER SET utf8 ;

USE `tallerDb` ;

-- -----------------------------------------------------
-- Table `tallerDb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerDb`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `motivo` VARCHAR(45) NULL,
  `fechaIngreso` DATE NULL,
  `fechaEntrega` DATE NULL,
  PRIMARY KEY (`idVehiculo`),
  UNIQUE KEY `placa_UNIQUE` (`placa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerDb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerDb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `Vehiculo_idVehiculo` INT NULL,
  `rol` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE KEY `cedula_UNIQUE` (`cedula` ASC),
  UNIQUE KEY `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_Persona_Vehiculo_idx` (`Vehiculo_idVehiculo` ASC),
  CONSTRAINT `fk_Persona_Vehiculo`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `tallerDb`.`Vehiculo` (`idVehiculo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerDb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerDb`.`Servicios` (
  `idServicios` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `tiempo` FLOAT NULL,
  `precio` FLOAT NULL,
  `Vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idServicios`),
  INDEX `fk_Servicios_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC),
  CONSTRAINT `fk_Servicios_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `tallerDb`.`Vehiculo` (`idVehiculo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- insertando datos de prueba 
-- Insertar usuario Administrador con contraseña 1234
INSERT INTO `persona` (`idPersona`, `nombre`, `apellido`, `cedula`, `telefono`, `email`, `usuario`, `contraseña`, `direccion`, `Vehiculo_idVehiculo`, `rol`, `cargo`) VALUES (NULL, NULL, NULL, '1', NULL, NULL, 'admin', 'jmcRXc9CttBo2cVdW1b5Tw==', NULL, NULL, 'admin', 'administrador');
-- Insertar una empleado 
INSERT INTO `tallerDb`.`Persona`
  (`nombre`, `apellido`, `cedula`, `telefono`, `email`, `usuario`, `contraseña`, `direccion`, `Vehiculo_idVehiculo`, `rol`, `cargo`)
VALUES
  ('Juan', 'Pérez', '12345678', '9321564587', 'juanpe@gmail.com', 'jupe', 'jmcRXc9CttBo2cVdW1b5Tw==', 'Calle 1', NULL, 'standard', 'Mecánico');

-- Insertar un vehículo y relacionarlo con una persona
INSERT INTO `tallerDb`.`Vehiculo`
  (`placa`, `tipo`, `estado`, `motivo`, `fechaIngreso`, `fechaEntrega`)
VALUES
  ('ABC123', 'Automóvil', 'En taller', 'Revisión de frenos', '2023-05-08', '2023-05-10');
INSERT INTO `tallerDb`.`Persona`
  (`nombre`, `apellido`, `cedula`, `telefono`, `email`, `usuario`, `contraseña`, `direccion`, `Vehiculo_idVehiculo`, `rol`, `cargo`)
VALUES
  ('María', 'González', '87654321', '6985125874', 'mariago@gmail.com', 'mago', 'jmcRXc9CttBo2cVdW1b5Tw==', 'Calle 2', LAST_INSERT_ID(), NULL, NULL);

-- Insertar un servicio y relacionarlo con un vehículo
INSERT INTO `tallerDb`.`Servicios`
  (`tipo`, `descripcion`, `tiempo`, `precio`, `Vehiculo_idVehiculo`)
VALUES
  ('Revisión', 'Revisión de frenos', 1.5, 100, 1);
